### ISSUE TITLE
Remove .travis.yml file 

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/chrome-cookie-path#13]

**Comment by Ebukachuqz** [comment]
Hi @arshadkazmi42 can I connect with you on twitter?

**Comment by arshadkazmi42** [comment]
> Hi @arshadkazmi42 can I connect with you on twitter?

Sure. My twitter handdle is https://twitter.com/arshadkazmi42

**Comment by Ebukachuqz** [comment]
Alright Thanks Arshad
